CREATE VIEW SeCoGEST.Statistiche_Fatturato
AS
SELECT        'SECOGES' AS AZIENDA, TESTA.ESERCIZIO, TESTA.NUMERODOC AS NUMERO, TESTA.DATADOC AS DATA, MONTH(TESTA.DATADOC) AS MESE, YEAR(TESTA.DATADOC) AS ANNO, TESTA.CODCLIFOR AS CODICECLIENTE, 
                         ANAG.DSCCONTO1 + ' ' + ANAG.DSCCONTO2 AS CLIENTE, ANAG.INDIRIZZO, ANAG.CAP, ANAG.LOCALITA, ANAG.PROVINCIA, ANAG.CODFISCALE, ANAG.PARTITAIVA, RIGA.TOTNETTORIGAEURO AS TOTALEDOCUMENTO, 
                         RIS.CODSETTORE, SETT.DESCRIZIONE AS SETTORE, AA.CODICE AS CODICECARTICOLO, AA.CATEGORIA AS CODICECATEGORIA, CATS.DESCRIZIONE AS DESCRIZIONECATEGORIA, 
                         AA.CODCATEGORIASTAT AS CODICECATEGORIASTATISTICA, CATSTAT.DESCRIZIONE AS DESCRIZIONECATEGORIASTATISTICA, AA.GRUPPO AS CODICEGRUPPO, GRUPPO.DESCRIZIONE AS DESCRIZIONEGRUPPO, 
                         TESTA.CODAGENTE1, TESTA.CODAGENTE2, TESTA.CODAGENTE3, RIGA.CONTOCDC AS CENTRODICOSTO
FROM            [GRPSCG].[dbo].TESTEDOCUMENTI TESTA INNER JOIN
                         [GRPSCG].[dbo].PARAMETRIDOC PD ON PD.CODICE = TESTA.TIPODOC INNER JOIN
                         [GRPSCG].[dbo].ANAGRAFICACF ANAG ON ANAG.CODCONTO = TESTA.CODCLIFOR INNER JOIN
                         [GRPSCG].[dbo].ANAGRAFICARISERVATICF RIS ON RIS.CODCONTO = TESTA.CODCLIFOR AND RIS.ESERCIZIO = TESTA.ESERCIZIO LEFT OUTER JOIN
                         [GRPSCG].[dbo].TABSETTORI SETT ON SETT.CODICE = RIS.CODSETTORE INNER JOIN
                         [GRPSCG].[dbo].RIGHEDOCUMENTI RIGA ON TESTA.PROGRESSIVO = RIGA.IDTESTA INNER JOIN
                         [GRPSCG].[dbo].ANAGRAFICAARTICOLI AA ON AA.CODICE = RIGA.CODART INNER JOIN
                         [GRPSCG].[dbo].TABCATEGORIE CATS ON CATS.CODICE = AA.CATEGORIA INNER JOIN
                         [GRPSCG].[dbo].TABCATEGORIESTAT CATSTAT ON CATSTAT.CODICE = AA.CODCATEGORIASTAT INNER JOIN
                         [GRPSCG].[dbo].TABGRUPPI GRUPPO ON GRUPPO.CODICE = AA.GRUPPO
WHERE        PD.TIPO = 'F' AND ANAG.PARTITAIVA NOT IN ('14243311009', '02913430985', '11692170969', '16072171008', '06947020829') AND LEFT(TESTA.CODCLIFOR, 1) = 'C'
UNION ALL
SELECT        'LTA' AS AZIENDA, TESTA.ESERCIZIO, TESTA.NUMERODOC AS NUMERO, TESTA.DATADOC AS DATA, MONTH(TESTA.DATADOC) AS MESE, YEAR(TESTA.DATADOC) AS ANNO, TESTA.CODCLIFOR AS CODICECLIENTE, 
                         ANAG.DSCCONTO1 + ' ' + ANAG.DSCCONTO2 AS CLIENTE, ANAG.INDIRIZZO, ANAG.CAP, ANAG.LOCALITA, ANAG.PROVINCIA, ANAG.CODFISCALE, ANAG.PARTITAIVA, RIGA.TOTNETTORIGAEURO AS TOTALEDOCUMENTO, 
                         RIS.CODSETTORE, SETT.DESCRIZIONE AS SETTORE, AA.CODICE AS CODICECARTICOLO, AA.CATEGORIA AS CODICECATEGORIA, CATS.DESCRIZIONE AS DESCRIZIONECATEGORIA, 
                         AA.CODCATEGORIASTAT AS CODICECATEGORIASTATISTICA, CATSTAT.DESCRIZIONE AS DESCRIZIONECATEGORIASTATISTICA, AA.GRUPPO AS CODICEGRUPPO, GRUPPO.DESCRIZIONE AS DESCRIZIONEGRUPPO, 
                         TESTA.CODAGENTE1, TESTA.CODAGENTE2, TESTA.CODAGENTE3, RIGA.CONTOCDC AS CENTRODICOSTO
FROM            [LTASRL].[dbo].TESTEDOCUMENTI TESTA INNER JOIN
                         [LTASRL].[dbo].PARAMETRIDOC PD ON PD.CODICE = TESTA.TIPODOC INNER JOIN
                         [LTASRL].[dbo].ANAGRAFICACF ANAG ON ANAG.CODCONTO = TESTA.CODCLIFOR INNER JOIN
                         [LTASRL].[dbo].ANAGRAFICARISERVATICF RIS ON RIS.CODCONTO = TESTA.CODCLIFOR AND RIS.ESERCIZIO = TESTA.ESERCIZIO LEFT OUTER JOIN
                         [LTASRL].[dbo].TABSETTORI SETT ON SETT.CODICE = RIS.CODSETTORE INNER JOIN
                         [LTASRL].[dbo].RIGHEDOCUMENTI RIGA ON TESTA.PROGRESSIVO = RIGA.IDTESTA INNER JOIN
                         [LTASRL].[dbo].ANAGRAFICAARTICOLI AA ON AA.CODICE = RIGA.CODART INNER JOIN
                         [LTASRL].[dbo].TABCATEGORIE CATS ON CATS.CODICE = AA.CATEGORIA INNER JOIN
                         [LTASRL].[dbo].TABCATEGORIESTAT CATSTAT ON CATSTAT.CODICE = AA.CODCATEGORIASTAT INNER JOIN
                         [LTASRL].[dbo].TABGRUPPI GRUPPO ON GRUPPO.CODICE = AA.GRUPPO
WHERE        PD.TIPO = 'F' AND ANAG.PARTITAIVA NOT IN ('14243311009', '02913430985', '11692170969', '16072171008', '06947020829') AND LEFT(TESTA.CODCLIFOR, 1) = 'C'
UNION ALL
SELECT        'LTM' AS AZIENDA, TESTA.ESERCIZIO, TESTA.NUMERODOC AS NUMERO, TESTA.DATADOC AS DATA, MONTH(TESTA.DATADOC) AS MESE, YEAR(TESTA.DATADOC) AS ANNO, TESTA.CODCLIFOR AS CODICECLIENTE, 
                         ANAG.DSCCONTO1 + ' ' + ANAG.DSCCONTO2 AS CLIENTE, ANAG.INDIRIZZO, ANAG.CAP, ANAG.LOCALITA, ANAG.PROVINCIA, ANAG.CODFISCALE, ANAG.PARTITAIVA, RIGA.TOTNETTORIGAEURO AS TOTALEDOCUMENTO, 
                         RIS.CODSETTORE, SETT.DESCRIZIONE AS SETTORE, AA.CODICE AS CODICECARTICOLO, AA.CATEGORIA AS CODICECATEGORIA, CATS.DESCRIZIONE AS DESCRIZIONECATEGORIA, 
                         AA.CODCATEGORIASTAT AS CODICECATEGORIASTATISTICA, CATSTAT.DESCRIZIONE AS DESCRIZIONECATEGORIASTATISTICA, AA.GRUPPO AS CODICEGRUPPO, GRUPPO.DESCRIZIONE AS DESCRIZIONEGRUPPO, 
                         TESTA.CODAGENTE1, TESTA.CODAGENTE2, TESTA.CODAGENTE3, RIGA.CONTOCDC AS CENTRODICOSTO
FROM            [LTMSRL].[dbo].TESTEDOCUMENTI TESTA INNER JOIN
                         [LTMSRL].[dbo].PARAMETRIDOC PD ON PD.CODICE = TESTA.TIPODOC INNER JOIN
                         [LTMSRL].[dbo].ANAGRAFICACF ANAG ON ANAG.CODCONTO = TESTA.CODCLIFOR INNER JOIN
                         [LTMSRL].[dbo].ANAGRAFICARISERVATICF RIS ON RIS.CODCONTO = TESTA.CODCLIFOR AND RIS.ESERCIZIO = TESTA.ESERCIZIO LEFT OUTER JOIN
                         [LTMSRL].[dbo].TABSETTORI SETT ON SETT.CODICE = RIS.CODSETTORE INNER JOIN
                         [LTMSRL].[dbo].RIGHEDOCUMENTI RIGA ON TESTA.PROGRESSIVO = RIGA.IDTESTA INNER JOIN
                         [LTMSRL].[dbo].ANAGRAFICAARTICOLI AA ON AA.CODICE = RIGA.CODART INNER JOIN
                         [LTMSRL].[dbo].TABCATEGORIE CATS ON CATS.CODICE = AA.CATEGORIA INNER JOIN
                         [LTMSRL].[dbo].TABCATEGORIESTAT CATSTAT ON CATSTAT.CODICE = AA.CODCATEGORIASTAT INNER JOIN
                         [LTMSRL].[dbo].TABGRUPPI GRUPPO ON GRUPPO.CODICE = AA.GRUPPO
WHERE        PD.TIPO = 'F' AND ANAG.PARTITAIVA NOT IN ('14243311009', '02913430985', '11692170969', '16072171008', '06947020829') AND LEFT(TESTA.CODCLIFOR, 1) = 'C'
UNION ALL
SELECT        'LTH' AS AZIENDA, TESTA.ESERCIZIO, TESTA.NUMERODOC AS NUMERO, TESTA.DATADOC AS DATA, MONTH(TESTA.DATADOC) AS MESE, YEAR(TESTA.DATADOC) AS ANNO, TESTA.CODCLIFOR AS CODICECLIENTE, 
                         ANAG.DSCCONTO1 + ' ' + ANAG.DSCCONTO2 AS CLIENTE, ANAG.INDIRIZZO, ANAG.CAP, ANAG.LOCALITA, ANAG.PROVINCIA, ANAG.CODFISCALE, ANAG.PARTITAIVA, RIGA.TOTNETTORIGAEURO AS TOTALEDOCUMENTO, 
                         RIS.CODSETTORE, SETT.DESCRIZIONE AS SETTORE, AA.CODICE AS CODICECARTICOLO, AA.CATEGORIA AS CODICECATEGORIA, CATS.DESCRIZIONE AS DESCRIZIONECATEGORIA, 
                         AA.CODCATEGORIASTAT AS CODICECATEGORIASTATISTICA, CATSTAT.DESCRIZIONE AS DESCRIZIONECATEGORIASTATISTICA, AA.GRUPPO AS CODICEGRUPPO, GRUPPO.DESCRIZIONE AS DESCRIZIONEGRUPPO, 
                         TESTA.CODAGENTE1, TESTA.CODAGENTE2, TESTA.CODAGENTE3, RIGA.CONTOCDC AS CENTRODICOSTO
FROM            [LTH].[dbo].TESTEDOCUMENTI TESTA INNER JOIN
                         [LTH].[dbo].PARAMETRIDOC PD ON PD.CODICE = TESTA.TIPODOC INNER JOIN
                         [LTH].[dbo].ANAGRAFICACF ANAG ON ANAG.CODCONTO = TESTA.CODCLIFOR INNER JOIN
                         [LTH].[dbo].ANAGRAFICARISERVATICF RIS ON RIS.CODCONTO = TESTA.CODCLIFOR AND RIS.ESERCIZIO = TESTA.ESERCIZIO LEFT OUTER JOIN
                         [LTH].[dbo].TABSETTORI SETT ON SETT.CODICE = RIS.CODSETTORE INNER JOIN
                         [LTH].[dbo].RIGHEDOCUMENTI RIGA ON TESTA.PROGRESSIVO = RIGA.IDTESTA INNER JOIN
                         [LTH].[dbo].ANAGRAFICAARTICOLI AA ON AA.CODICE = RIGA.CODART INNER JOIN
                         [LTH].[dbo].TABCATEGORIE CATS ON CATS.CODICE = AA.CATEGORIA INNER JOIN
                         [LTH].[dbo].TABCATEGORIESTAT CATSTAT ON CATSTAT.CODICE = AA.CODCATEGORIASTAT INNER JOIN
                         [LTH].[dbo].TABGRUPPI GRUPPO ON GRUPPO.CODICE = AA.GRUPPO
WHERE        PD.TIPO = 'F' AND ANAG.PARTITAIVA NOT IN ('14243311009', '02913430985', '11692170969', '16072171008', '06947020829') AND LEFT(TESTA.CODCLIFOR, 1) = 'C'
UNION ALL
SELECT        'RAND' AS AZIENDA, TESTA.ESERCIZIO, TESTA.NUMERODOC AS NUMERO, TESTA.DATADOC AS DATA, MONTH(TESTA.DATADOC) AS MESE, YEAR(TESTA.DATADOC) AS ANNO, TESTA.CODCLIFOR AS CODICECLIENTE, 
                         ANAG.DSCCONTO1 + ' ' + ANAG.DSCCONTO2 AS CLIENTE, ANAG.INDIRIZZO, ANAG.CAP, ANAG.LOCALITA, ANAG.PROVINCIA, ANAG.CODFISCALE, ANAG.PARTITAIVA, RIGA.TOTNETTORIGAEURO AS TOTALEDOCUMENTO, 
                         RIS.CODSETTORE, SETT.DESCRIZIONE AS SETTORE, AA.CODICE AS CODICECARTICOLO, AA.CATEGORIA AS CODICECATEGORIA, CATS.DESCRIZIONE AS DESCRIZIONECATEGORIA, 
                         AA.CODCATEGORIASTAT AS CODICECATEGORIASTATISTICA, CATSTAT.DESCRIZIONE AS DESCRIZIONECATEGORIASTATISTICA, AA.GRUPPO AS CODICEGRUPPO, GRUPPO.DESCRIZIONE AS DESCRIZIONEGRUPPO, 
                         TESTA.CODAGENTE1, TESTA.CODAGENTE2, TESTA.CODAGENTE3, RIGA.CONTOCDC AS CENTRODICOSTO
FROM            [RANDSRL].[dbo].TESTEDOCUMENTI TESTA INNER JOIN
                         [RANDSRL].[dbo].PARAMETRIDOC PD ON PD.CODICE = TESTA.TIPODOC INNER JOIN
                         [RANDSRL].[dbo].ANAGRAFICACF ANAG ON ANAG.CODCONTO = TESTA.CODCLIFOR INNER JOIN
                         [RANDSRL].[dbo].ANAGRAFICARISERVATICF RIS ON RIS.CODCONTO = TESTA.CODCLIFOR AND RIS.ESERCIZIO = TESTA.ESERCIZIO LEFT OUTER JOIN
                         [RANDSRL].[dbo].TABSETTORI SETT ON SETT.CODICE = RIS.CODSETTORE INNER JOIN
                         [RANDSRL].[dbo].RIGHEDOCUMENTI RIGA ON TESTA.PROGRESSIVO = RIGA.IDTESTA INNER JOIN
                         [RANDSRL].[dbo].ANAGRAFICAARTICOLI AA ON AA.CODICE = RIGA.CODART INNER JOIN
                         [RANDSRL].[dbo].TABCATEGORIE CATS ON CATS.CODICE = AA.CATEGORIA INNER JOIN
                         [RANDSRL].[dbo].TABCATEGORIESTAT CATSTAT ON CATSTAT.CODICE = AA.CODCATEGORIASTAT INNER JOIN
                         [RANDSRL].[dbo].TABGRUPPI GRUPPO ON GRUPPO.CODICE = AA.GRUPPO
WHERE        PD.TIPO = 'F' AND ANAG.PARTITAIVA NOT IN ('14243311009', '02913430985', '11692170969', '16072171008', '06947020829') AND LEFT(TESTA.CODCLIFOR, 1) = 'C'
GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPaneCount', @value = 1, @level0type = N'SCHEMA', @level0name = N'SeCoGEST', @level1type = N'VIEW', @level1name = N'Statistiche_Fatturato';


GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPane1', @value = N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4[30] 2[40] 3) )"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2[66] 3) )"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 5
   End
   Begin DiagramPane = 
      PaneHidden = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 29
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 2970
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      PaneHidden = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
', @level0type = N'SCHEMA', @level0name = N'SeCoGEST', @level1type = N'VIEW', @level1name = N'Statistiche_Fatturato';

