//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeCoGEST.Entities.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.13;Initial Catalog=GRPSCG;Persist Security Info=True;User I" +
            "D=sa;Password=mclcacsql")]
        public string GRPSCGConnectionString {
            get {
                return ((string)(this["GRPSCGConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NBGIANLUIGI;Initial Catalog=GRPSCG;Persist Security Info=True;User ID" +
            "=Gestionale;Password=mclcacgest")]
        public string GRPSCGConnectionString1 {
            get {
                return ((string)(this["GRPSCGConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NBCOFFINARDI;Initial Catalog=GRPSCG;Persist Security Info=True;User I" +
            "D=sa;Password=mclcacsql")]
        public string GRPSCGConnectionString2 {
            get {
                return ((string)(this["GRPSCGConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NBCOFFINARDI;Initial Catalog=GRPSCG;Integrated Security=True")]
        public string GRPSCGConnectionString3 {
            get {
                return ((string)(this["GRPSCGConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC-COFFINARDI\\SQLEXPRESS;Initial Catalog=GRPSCG;Persist Security Info" +
            "=True;User ID=sa;Password=mclcacsql")]
        public string GRPSCGConnectionString4 {
            get {
                return ((string)(this["GRPSCGConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NBCOFFINARDI\\SQLEXPRESS;Initial Catalog=GRPSCG;Persist Security Info=" +
            "True;User ID=sa;Password=mclcacsql")]
        public string GRPSCGConnectionString5 {
            get {
                return ((string)(this["GRPSCGConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC-GIANLUIGI\\SQLEXPRESS01;Initial Catalog=GRPSCG;Integrated Security=" +
            "True")]
        public string GRPSCGConnectionString6 {
            get {
                return ((string)(this["GRPSCGConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.13\\SQL2017;Initial Catalog=test_metodo;Persist Security Inf" +
            "o=True;User ID=Gestionale;Password=mclcacgest")]
        public string test_metodoConnectionString {
            get {
                return ((string)(this["test_metodoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.12;Initial Catalog=GestGRPSCG;Persist Security Info=True;Us" +
            "er ID=Gestionale;Password=mclcacgest;Encrypt=True;TrustServerCertificate=True")]
        public string GestGRPSCGConnectionString {
            get {
                return ((string)(this["GestGRPSCGConnectionString"]));
            }
        }
    }
}
